name: Build 

on: push

jobs:
  PlatformIO-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install PlatformIO
        run: |
          pip install -U platformio
          platformio update
      - name: "PlatformIO: Build"
        run: platformio run